apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config-file
  labels:
    app: kibana-logging
data:
  kibana.yml: |-
    server.name: kibana-logging
    server.host: "0"
    elasticsearch.url: http://elasticsearch:9200
    elasticsearch.username: elastic
    elasticsearch.password: changeme