# MYSQL_PASSWORD
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
type: Opaque
data:
  username: dXNlcg==
  password: cGFzcw==

---
# MYSQL_ROOT_PASSWORD
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root
type: Opaque
data:
  username: cm9vdA==
  password: bXlzcWxwYXNz
