apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-scheduler-metrics-svc
  labels:
    k8s-app: kube-scheduler
    prom-target: kube-scheduler
    component: prometheus
    task: scrape
  annotations:
    prometheus.io/scrape: 'true'
spec:
  clusterIP: None
  ports:
  - name: kube-scheduler
    port: 10251
  selector:
    k8s-app: kube-scheduler
