apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-metrics-svc
  labels:
    k8s-app: kube-controller-manager
    prom-target: kube-controller-manager
    component: prometheus
    task: scrape
  annotations:
    prometheus.io/scrape: 'true'
spec:
  clusterIP: None
  ports:
  - name: kube-controller-manager
    port: 10252
  selector:
    k8s-app: kube-controller-manager
