apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-fail2
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 0.3
  - name: tomcat
    image: tomcat
    resources:
      requests:
        memory: 100Mi
