apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
  labels:
    app: grafana
    job: grafana
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: grafana
  ports:
  - name: grafana
    protocol: TCP
    port: 80
    targetPort: 3000
