apiVersion: v1
kind: LimitRange
metadata:
  name: project1-limit-range
spec:
  limits:
  - default:
      cpu: 0.5
      memory: 512Mi
    defaultRequest:
      cpu: 0.25
      memory: 256Mi
    type: Container
