apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-flags
  namespace: monitoring
  labels:
    app: prometheus
data:
  # Check "prometheus --help" for more flags
  STORAGE_LOCAL_RETENTION: 7d
