apiVersion: v1
kind: Pod
metadata:
  name: secret-acces-ev
spec:
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh", "-c", "while : ;do echo $MY_PASSWORD; sleep 10; done"]
    env:
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mypassword
              key: mypassword
