apiVersion: v1
kind: Pod
metadata:
  name: clusterip-dns-chk
spec:
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh", "-c", "while : ;do curl http://nginx-service.default:_http_tcp.nginx-service.default/; sleep 10; done"]
